
version: '3'
services:
  app:
    command: scrapy list | xargs -n 1 scrapy crawl
    build: .
    volumes:
      - .:/var/www/html/cinecrawler
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: cinecrawler
      PGDATA: /tmp
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080